# Generated by Django 3.1 on 2025-11-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_data',
            new_name='created_date',
        ),
    ]
